// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

import "./globals.css";
import Navbar from "./components/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "./components/Footer";

export const metadata = {
  title: "DriveFleet | Premium Car Rental Platform",
  description: "Find the Right Car for Every Journey",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#F8FAFC] text-[#0B131F] antialiased min-h-screen flex flex-col justify-between">
        
        {/* Toast notifications container for clean error/success alerts */}
        <Toaster position="top-center" reverseOrder={false} />
        
        {/* Perfectly aligned global Navbar */}
       
        
        {/* Render page routes dynamically here */}
        <main className="flex-grow">
           <Navbar />
          {children}
          <Footer />
        </main>
         {/* Footer will be added here in the future */}
      </body>
    </html>
  );
}